name: Menus
version: '${project.version}'
api-version: 1.13
main: org.denizenmc.menus.Menus
authors: [ Denizen ]
description: Internal menus library.
depend: [PlaceholderAPI]
commands:
  menus:
    description: Open navigation menu for Menus.
